const ELECTRICITY = 1;
const ENERGY_SCEE_WIDHOUT_ICMS = 2;
const COMPENSATED_ENERGY_GDI = 3;
const MUNICIPAL_PUBLIC_LIGHTING_CONTRIBUTION = 4;
const COMPENSATION_FOR_DAMAGES = 5;

export { 
    ELECTRICITY, 
    ENERGY_SCEE_WIDHOUT_ICMS,
    COMPENSATED_ENERGY_GDI,
    MUNICIPAL_PUBLIC_LIGHTING_CONTRIBUTION,
    COMPENSATION_FOR_DAMAGES
};